spring.application.name=microservicio-pedidos

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/micro_pedido}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:juliana}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false